
% Directory of the *.m files that will be updated
fileDirectory = '../../..';
[thisDirectory,~] = fileparts(mfilename('fullpath'));
files = dir(fullfile(thisDirectory,fileDirectory,'**/*.m'));
% files = dir(fullfile(thisDirectory,fileDirectory,'wecSimTest.m'));

% Remove v5Renaming.m and updateNaming.m from file list
i1 = find(contains({files.name},'v5Renaming.m'));
i2 = find(contains({files.name},'updateNaming.m'));
files(i1) = [];
files(i2) = [];

% Combine file paths and file names
files = fullfile({files.folder},{files.name});

% BEMIO variables to rename
variables = {...
    'Read_WAMIT', 'readWAMIT';...
    'Read_NEMOH', 'readNEMOH';...
    'Read_AQWA', 'readAQWA';...
    'Read_CAPYTAINE', 'readCAPYTAINE';...
    'Combine_BEM', 'combineBEM';...
    'Radiation_IRF_SS', 'radiationIRFSS';...
    'Radiation_IRF', 'radiationIRF';... % how to avoid mixing this up with radiation_IRF_SS?
    'Excitation_IRF', 'excitationIRF';...
    'Write_H5', 'writeH5';...
    'plotBemio', 'plotBEMIO';...
    'Normalize','normalizeBEM';... % 'normalize' is a standard MATLAB function and should be avoided
    'Load_H5','loadH5';...
    'h5bem_create','h5bemCreate';...
    'h5bem_writeBody','h5bemWriteBody';...
    'h5bem_writeParameters','h5bemWriteParameters'};

for k = 1:size(variables,1)
    oldVar = variables{k,1};
    newVar = variables{k,2};
    updateNaming(files,oldVar,newVar);
end
