load_system('WECSim_Lib_Body_Elements')
BlockPaths = find_system(['WECSim_Lib_Body_Elements/' ...
    'Rigid Body/Hydrodynamic Body/Wave Radiation Forces Calculation' ...
    '/SS CI and Constant-Damping-CoeVariant Subsystem/' ...
    'FIR Filter Calculation/FIR Filter Matrix/FIR filter row/'],'Type','Block');
handle = getSimulinkBlockHandle(['WECSim_Lib_Body_Elements/' ...
    'Rigid Body/Hydrodynamic Body/Wave Radiation Forces Calculation' ...
    '/SS CI and Constant-Damping-CoeVariant Subsystem/' ...
    'FIR Filter Calculation/FIR Filter Matrix/FIR filter row' ...
    '/Add']);
ObjectParameters = get_param(handle,'ObjectParameters');
DialogParameters = get_param(handle,'DialogParameters');
p = Simulink.Mask.get(handle);
MaskVars = p.getWorkspaceVariables;