% %#ok<*NASGU>
% % Suppresing "unused variables" warnings. The variables created in initialization
% % code can be used by the child blocks or in the icon drawing code. 
% 
% % Initialization code section
% function initialization()
% cb = gcb;
% nWaves = size(waveGroup,2);
% for iWG = 2:nWaves
%     try 
%         find_system([cb,'/Wave Diffraction and Excitation Force Calculation/Linear Wave Excitation Force Variant Subsystem',num2str(iWG)],'Type','Block');
%     catch
%         add_block([cb,'/Wave Diffraction and Excitation Force Calculation/Linear Wave Excitation Force Variant Subsystem']...
%             ,[cb,'Wave Diffraction and Excitation Force Calculation/Linear Wave Excitation Force Variant Subsystem',num2str(iWG)],'MakeNameUnique','off',...
%                    'Position',[400,200*iWG,580,40+200*iWG],'BackgroundColor','white');
%         set_param([cb,'/Wave Diffraction and Excitation Force Calculation/Linear Wave Excitation Force Variant Subsystem',num2str(iWG)],...
%                'Nwave',sprintf('waves(%d)',iWG) );
% 
%         add_line(cb,...
%            ['FexcInputs/1'],...
%             ['/Wave Diffraction and Excitation Force Calculation/Linear Wave Excitation Force Variant Subsystem',num2str(iWG),'/1'],...
%             'autorouting','on');
%            add_line(cb,...
%            ['FexcInputs/2'],...
%             ['/Wave Diffraction and Excitation Force Calculation/Linear Wave Excitation Force Variant Subsystem',num2str(iWG),'/2'],...
%             'autorouting','on');
%         signlist = get_param([cb,'/Add'],'Inputs');   
%         set_param([cb,'/Add'],'Inputs',[signlist,'+']);
%         add_line(cb,...
%         ['/Wave Diffraction and Excitation Force Calculation/Linear Wave Excitation Force Variant Subsystem',num2str(iWG),'/1'],...
%         sprintf('Add/%d',length(signlist)+1),...
%         'autorouting','on');
%     end
% end 
% end
% 
% % Parameter callback section
