# disable blank issues
blank_issues_enabled: false

# link to documentation
contact_links:
  - name: Review WEC-Sim documentation
    url: https://wec-sim.github.io/WEC-Sim/main/index.html
    about: Please review documentation and previous issues before asking questions.