name: Run MATLAB tests on main branch
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
jobs:
  run_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-latest]
        release: [R2023a, R2023b, R2024a, R2024b]
    name: ${{ matrix.release }} on ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Check out LFS objects
        run: git lfs checkout
      - name: Install MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          release: ${{ matrix.release }}
          products: Simulink Simscape Simscape_Multibody
      - name: Install WEC-Sim, run tests and generate artifacts
        uses: matlab-actions/run-command@v2
        with:
          command: |
            addpath(genpath('source')),
            set_param(0, 'ErrorIfLoadNewModel', 'off'),
            results = wecSimTest,
            assertSuccess(results);
          startup-options: -noFigureWindows
